// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA1gd1R5kmWw9c6CdMzn_a43LJtOsm0FU',
    appId: '1:1018625403742:android:1a3f6d59cdf0f417f43dcf',
    messagingSenderId: '1018625403742',
    projectId: 'el-chaski-delivery-bolivia',
    databaseURL: 'https://el-chaski-delivery-bolivia.firebaseio.com',
    storageBucket: 'el-chaski-delivery-bolivia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtww9AL1bETUbyak01Z87Hus77OiOclE',
    appId: '1:1018625403742:ios:dd765c476d1e1502f43dcf',
    messagingSenderId: '1018625403742',
    projectId: 'el-chaski-delivery-bolivia',
    databaseURL: 'https://el-chaski-delivery-bolivia.firebaseio.com',
    storageBucket: 'el-chaski-delivery-bolivia.appspot.com',
    androidClientId: '1018625403742-4l7v71ntnf2dajj02761kdfsib355rfe.apps.googleusercontent.com',
    iosClientId: '1018625403742-duqpfcbiti60u6t2jttteqcvarbno97r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ariztiaApp',
  );
}
